### ISSUE TITLE
Appointment Scheduling

### ISSUE THREAD

**Issue by DanielCaspers** [DanielCaspers/CA-Portal#1]
**Motivation**
Customers should be able to schedule appointments for routine maintenance and service on their vehicles. 

**Acceptance criteria**
1. A warning should be provided to users that
1.1. Need rental cars, which may not be available
1.2. Require only basic services to be performed, including
1.2.1. Oil changes
1.2.2 Tire rotations

2. Instructions for how and when to drop off the car

3. Reiterate store hour info

4. Appointment scheduling should allow the user to 
4.1. Select a date for service based on available dates as exposed from a MurphyAuto API.
4.2. Select the vehicle to schedule the appointment for
4.3. Select one or more common problem descriptions from a list exposed from a MurphyAuto API
4.4. Provide free text to 
4.4.1 Ask questions
4.4.2 Provide any useful detail or background
4.4.3. Express their concern if it isn't provided in 4.3.
4.5 Select from a list of known recommended services (#25) for their vehicle to add to the list of things to address.
4.5.1 This list should not include ignored/muted recommended services
4.5.2 This list should be sorted by decreasing severity. 
4.6. Select from a list of vehicle specific coupons (#1) to include additional billable work.

**Comment by DanielCaspers** [comment]
@scaspers @YoMurphy the most critical changes to review from wireframe #16 flow 1 is the additional textbox at the bottom of the form, and if there are additional short circuit criteria to evaluate.

**Comment by scaspers** [comment]
I think I need to talk to you about this. I am not sure I understand what the text box at the bottom is going to be for? 
Or, what other short circuit criteria?

**Comment by DanielCaspers** [comment]
Read full requirement and see if you still have Qs. Short circuit meaning customer told not to schedule

**Comment by DanielCaspers** [comment]
@scaspers  @YoMurphy Appointment scheduling is coming along nicely with real data now! 

Before we can go any further, we should discuss how you would like to associate RS's and Coupons with scheduling, what order they should come in the stepper flow, etc. 

Once we've figured that out, I'll also need an API to submit the appointment to you.

**Comment by DanielCaspers** [comment]
Updated decisions from discussion with @scaspers.

Write the human-readable description instead of the category to the common issues field. 

Coupon scheduling will be 
1) If existing vehicle is being scheduled for, use coupons for vehicle for client.
2) If new vehicle is being scheduled, use coupons for client.

**Comment by DanielCaspers** [comment]
@scaspers @YoMurphy, real appointments can now be scheduled using the app for new or existing vehicles.

As far as I can tell, the remaining needs for this feature are 

1) Users must be able to add recommended services to an order. API support will be required unless you advise my implementation otherwise (perhaps in work description?)

2) Coupons will need a way to specify if this is required at schedule time. API support will be required. 
The other option is to _not_ allow them to attach them to the order, and let the burden be on them to bring it up when they are billing out.

**Comment by scaspers** [comment]
Example of the string formatting when inserting an RS into a work description.  This is what it looks like in the json. WO# 004609021 on d3-devel
`
    "workDesc": [
        "WATER PUMP, REPLACE                        LVL=1 [609019] 4067",
        "ROTATE TIRES",
        "CHECK BRAKES"
    ],
    `
The RS looked like this:
`

    "vehicleRS": [
        {
            "coNumber": "004",
            "id": "1903236111",
            "desc": "WATER PUMP, REPLACE           ",
            "level": "1",
            "orderID": "609019",
            "date": 1581141600,
            "techNum": "4067",
            "DIlink": "",
            "estID": "1903235610",
            "notificationCnt": 0
        }
    ],


`

**Comment by DanielCaspers** [comment]
@scaspers go ahead and pull the latest from Azure DevOps and test when you like. https://dev.azure.com/DanielCaspers/Murphy%20Automotive/_build/results?buildId=50&view=results

**Comment by DanielCaspers** [comment]
@scaspers  @YoMurphy awaiting for you to "user acceptance test" and close this, or provide additional feedback on what more is required. Thanks!

**Comment by scaspers** [comment]
"What should we look into" will not allow user to advance if only common concerns are added.

**Comment by DanielCaspers** [comment]
@scaspers  form validation logic should be fixed, but I was unable to verify because the API went down. Try on the latest build.

**Comment by DanielCaspers** [comment]
@scaspers for this work to be complete, you will need to add the information I specified in https://github.com/scaspers/D3-API/issues/25 in order for this to function as specified. 

All other requests for this feature have been completed. All future changes will be taken as change requests.
