### ISSUE TITLE
Vehicle Coupons

### ISSUE THREAD

**Issue by DanielCaspers** [DanielCaspers/CA-Portal#19]
**Motivation**
Customers should be able to see the coupons which are relevant to use for a given vehicle.

**Acceptance criteria**
- [x] 1. Coupons can be accessible via
- [x] 1.1 The vehicle list #17 
- [x] 1.2 The main navigation sidenav
- [x] 1.3. ~~An appointment scheduling step.~~ Remaining work will be approved during completion of #1 

- [x] 2. Upon accessing it, users shall see a list of available coupon images.
- [x] 2.1. These images should be returned as URLs or base64 encoded images from the MurphyAuto API.

- [x] 3. The coupons in the main navigation will contain all coupons for a client. 

- [x] 4.  The coupons available in 1.1 and 1.3 will be filtered based on the chosen vehicle. 

- [x] 5. Services cannot be scheduled from the coupons page launched via the main navigation sidenav (1.2). 

**Agreed upon change risks**
1. Given the current UI, its unclear whether or not we should support scheduling from the vehicle-specific coupon view, because it may be close enough to the scheduling view in the UI that we'll have too many cross-linked features. We have discussed the idea of pre-filling a vehicle and coupons in the scheduling view, but I think we should hold off on this for now.

**Comment by DanielCaspers** [comment]
Would we ever support a list of coupons, or would it only be the singular coupon for the next oil change?

**Comment by YoMurphy** [comment]
I feel we should always have a 2 or 3 coupons always shown through the scheduling process. First showing any relevant coupons to the service request and more for unrelated popular services to inspire other add-on sales.

**Comment by YoMurphy** [comment]
Add a link to the specials page inline with shown specials.

**Comment by scaspers** [comment]
I think that being able to see offers\coupons prior to scheduling and being able to initiate the scheduling process from an offer would be a good idea.
As for the coupons during the scheduling process steps, I think that it is a good idea for people to see them all the way through even though they are past the place of adding them as add-on sales can be inspired online and requested at check-in time also,  That is to say that it is typically never too late to inspire a sale.

**Comment by scaspers** [comment]
The "promos" api is now available.
See [https://d3-devel.murphyauto.net/api/v2/help](https://d3-devel.murphyauto.net/api/v2/help)

**Comment by DanielCaspers** [comment]
@scaspers @YoMurphy Below is a brief demo of the latest coupons functionality.

This feature ready for your final sign-off. We can take the appointment scheduling coupons flow approval during appointment scheduling. 

1) Responsive handling
![Untitled_ Nov 29 2019 7_50 PM](https://user-images.githubusercontent.com/6056563/69894168-a4cc1080-12e1-11ea-8135-62644b29667c.gif)

2) Coupons Flow from Sidenav and Vehicle Card
![MyCar - Murphy Automotive (3)](https://user-images.githubusercontent.com/6056563/69894199-2b80ed80-12e2-11ea-96a5-0c90d7c3ca45.gif)

Note: Clicking on a coupon also opens it in a new tab in case users need to zoom in and read details.

**Comment by DanielCaspers** [comment]
Updated decision after talking offline with @scaspers 

1) API will provide offer types. I will wait to proceed.

**Comment by scaspers** [comment]
promos endpoint now includes "offerCategory".

**Comment by DanielCaspers** [comment]
General offers and tire offers sections are now reinstated based on what is provided by the API. This is now feature complete and further modifications can be taken as a change order.
