### ISSUE TITLE
Account Settings

### ISSUE THREAD

**Issue by DanielCaspers** [DanielCaspers/CA-Portal#20]
**Motivation**
Customers should be able to view and manage their account information, such as their email addresses, password, and notification preferences.

**Acceptance criteria**
- [x] 1. Customers shall be able to see readonly information about their account
- [x] 1.1 First and last name
- [x] 1.2. Address

- [x] 2. Customers shall be able to manage their email addresses and phone numbers on the account.
- [x] 2.2. For each contact and medium (email/text), users shall be able to individually opt into or opt out of notification types.
- [x] 2.2.1. MurphyAuto will expose an API that describes the available notifications to configure. It will contain a list of objects describing
- [x] 2.2.1.1 The notification type (the form submission value in code)
- [x] 2.2.1.2. The display name ("Oil change reminders")

**Agreed upon change risks**
Customer's may have the ability to change their password from here (#20)

**Descoped requirements**
- [ ] 2.1. An indication shall be displayed on the primary account to indicate it is the account used when sending password reset emails.
Discussed with @scaspers that this is not necessary since the API currently does not expose this.

**Comment by DanielCaspers** [comment]
@scaspers not sure how granular you want the contact management, and if you have other ideas for handling the automatic extensibility of communication preference options.

**Comment by scaspers** [comment]
Acceptance with the following considerations:
1.3 read-only phone number may not be needed since we do not mark a number as primary in the client file (only on work orders)
2 is pending API changes.  (This may be handled outside of mycar)

**Comment by DanielCaspers** [comment]
@YoMurphy awaiting your approval. @scaspers approval criteria were added to the description.

**Comment by DanielCaspers** [comment]
@scaspers @YoMurphy The read-only name and address information is now accessible. 

We should discuss what else we'd like to do from here. Looks like we had some details to nail down judging by the original requirements and comments thread...

Below is a video of current features and responsive behavior, and a screenshot at desktop res.

![MyCar - Murphy Automotive](https://user-images.githubusercontent.com/6056563/69907338-11eead00-1399-11ea-9c35-e0f133135b05.gif)

![image](https://user-images.githubusercontent.com/6056563/69907341-3480c600-1399-11ea-80a3-df2cb6b08765.png)

**Comment by scaspers** [comment]
@DanielCaspers Check out the updated API and docs.  I also did some editing in postman which may be even better than the old docs.

**Comment by scaspers** [comment]
The clients endpoint has the ability to edit phone numbers and email addresses.  
The notification display names should be:
- Reminders
- VIP
- Promos


**IMPORTANT**
When updating clientPhone you must return all phone objects.
When updating clientEmail you must return all email address objects.
