### ISSUE TITLE
Dashboard Widgets

### ISSUE THREAD

**Issue by DanielCaspers** [DanielCaspers/CA-Portal#22]
**Motivation**
Customers shall be able to see any critical, important info that requires their attention or call to login right after they login.

**Acceptance criteria**
0. Customers shall be able to have access to one of each of the following widgets which are pre-defined in advance and not configurable by the user.

1. VIP Rewards
1.1 Current points balance
1.2 Points to next milestone 
1.3 A link for more detailed VIP rewards information (#18)

2. Recommended services (#25)
2.1 The list contains
2.1.1 Severity
2.1.2 Associated vehicle
2.1.3 Recommended service description
2.2 The list shall be permanently sorted from most severe to least severe.
2.3 The list shall only include the top 5/10 recommended services across all vehicles which
2.3.1 Are not ignored
2.3.2 Are "Immediate" or "Moderate" severity
2.4 If none match the condition, have an "All good" message showing no services needed.
2.5 For each vehicle, the user should be able to open up a link to a specific vehicle's combined RS list. 

3. Maintenance due
3.1. For each vehicle meeting threshold to be in the list,
3.1.1 Mileage due
3.1.2 Due date
3.1.3 The item to address (e.g. oil change, tire rotation, regular maintenance needs)
3.1.4 Associated vehicle
3.2 List is sorted by closest due date. 
3.3 If none match the condition, have an "All good" message showing no maintenance needed.
3.4 For each vehicle, the user should be able to open up a link to a specific vehicle's combined RS list. 
3.5. All of this data comes from a combined RS list of only maintenance level items. Hence, we don't show severity in this view. 

**Agreed upon change risks**
1. We may choose to merge the recommended services and maintenance due widgets if separating them doesn't feel right once we see it with real data.

**Comment by DanielCaspers** [comment]
@scaspers I came up with some ideas for dashboard widgets. Kick these around with Rick and lmk if you have any questions. I've posted an image for inspiration.

![image](https://user-images.githubusercontent.com/6056563/48876646-bf150980-edc4-11e8-989a-e91751a1f3bd.png)

**Comment by YoMurphy** [comment]
Great idea!
Oil Changes tab should be called Maintenance Due and could also indicate Tire Rotation or other future regular maintenance needs.

**Comment by DanielCaspers** [comment]
@YoMurphy which widgets do you think should be scoped in?

Is constraint 0 acceptable for now for minimum viable product?

**Comment by scaspers** [comment]
I think that Maintenance Due (could include RS's) and VIP are both valuable widgets.  I am riding the fence on the Account Financials unless they have a balance.  Not sure we want to put in someones face the amount they have put into there vehicles as it could invoke negative emotion.

**Comment by DanielCaspers** [comment]
Deferred ideas for widgets. 

3. Account financials
3.1 Current account balance outstanding
3.2. Dollars spent this year?

**Comment by DanielCaspers** [comment]
@scaspers when we get to implementation we can experiment with the idea of whether or not it makes sense to merge recommended services with maintenance due. I can see cases where it might be beneficial to separate them, because it may be difficult for cash-strapped customers to decide whether to do the recommended service or go over on their oil change if you put them in the same place.

**Comment by DanielCaspers** [comment]
@scaspers @YoMurphy Please write "approve" if you feel it is well enough defined, else we can further spec this out. I say let's play with the idea of keeping maintenance due and RSs for now, and I'll give you freedom to combine them into one widget later if you don't like how it turns out.

**Comment by YoMurphy** [comment]
Add 1.4 Exclusive VIP offers. 
And/or 
4. Special Offers widget

**Comment by YoMurphy** [comment]
1.2 Points to next milestone, I would move into 1.3 VIP detail page. To keep the widget small.

**Comment by YoMurphy** [comment]
Either 1.4 and/or 4. Offer pages should only show 1 or 2 teaser offers with link to more.

**Comment by DanielCaspers** [comment]
We've decided against the general user-facing dashboard view for this app in favor of a vehicle overview page as the landing page. We can reopen this issue if that changes.
