### ISSUE TITLE
Recommended Services

### ISSUE THREAD

**Issue by DanielCaspers** [DanielCaspers/CA-Portal#25]
**Motivation**
Customers should be able to see all of their unaddressed recommended services **for a single vehicle**.

**Acceptance criteria**

- [x] 1. Customers shall be presented with a list that contains
- [x] 1.1. Date
- [x] 1.2. Severity
- [x] 1.3. Recommended Service Description

- [x] 2. These shall be accessible on vehicles that need to show additional detail per #17 

3. A user shall be able to perform any of these actions on one or more recommended services
3.1 ~~**Schedule an online appointment to service**~~ Descoped in order to simplify the user experience. 
3.2 ~~**Request further info about this recommendation**~~ offloaded to #36 in order to simplify the user experience
3.3. ~~Mark service as completed elsewhere~~ offloaded to #35
3.4 ~~Muting and unmuting recommended services~~ offloaded to #35 
- [x] 4. The list shall be sorted primarily by severity, and secondarily by date in reverse chronological order. 

5. ~~A user shall be able to schedule service from this list.~~ (#1) Descoped in order to simplify the user experience. 
5.1 Clicking on this link when no selection is available will launch scheduling with the vehicle pre-selected
5.2. Clicking on this link when one or more RSs are selected will launch scheduling with both the vehicle and the recommended services pre-selected.

**Comment by YoMurphy** [comment]
This may add some complexity but would satisfy customer concern when trying to keep there vehicle records up to date.
Adding the ability to add Flags to any Recommended Service item. 
1. Schedule online Appointment to Service.
2. Request further information about this recommendation.
2. Service completed elsewhere.
2. Ignore or Hide Recommendation.
All these flags could then possibly be seen on DI at there next service for us to update or remove them.

**Comment by DanielCaspers** [comment]
Got some organizational questions based on the feedback.

1) **Who adds these flags? The customer, or the D3-API based on services scheduled?**
**1a) Who/what sees the flags?**

2) If you'd like to launch scheduling from Recommended Services, that makes perfect sense to me. 
That requirement should be specified in here and cross link to #1. Please confirm this is what you want and I'll adjust the requirement.

3) I don't see why we would use flags to request further info about a recommendation. I see this as a reason why we should provide a link to inspection history, or at least the last inspection. This way canned responses on the item can provide helpful details about the general problem, and inspection item notes can specifically describe what is going on in their case. 

4) If a customer marks a recommended service as completed elsewhere, are we then more generally advocating that they can "dismiss recommended services" in the same way a user can dismiss notifications? I see this as a constraint on D3-API mostly. Is dismissing meaning that it is wiped forever?

**Comment by scaspers** [comment]
These flags\links would be seen and can be selected by the customer.

- The schedule link would initiate the scheduling process with the RS pre-loaded in the vehicle needs section. In the case of multiple RS's being listed maybe it would be select boxes and a single schedule link.
- The further information link could initiate a text or email with the RS included in the message.
- Service completed elsewhere would be a flag set via D3-API that would cause us to reevaluate during the next inspection.
- The Hide option could maybe be saved in cookies\local storage that would allow customers to hide them from view but not remove them from database.  Then there could be a toggle to show\hide the hidden.

**Comment by DanielCaspers** [comment]
I can get on board with everything except hide / show. What value or ROI do you expect from that feature? How do you know if the feature achieves intended results?

**Comment by scaspers** [comment]
If a customer accidentally hide something how would they get it back?
If a customer wanted to hide some "Should Watch" or "Maintenance" RS's so they could focus on "Immediate" and "Moderate" and then deal with the others later??

**Comment by DanielCaspers** [comment]
@scaspers @YoMurphy I have not implemented the ability to perform actions yet.

Here's the latest progress with data from my account.

![MyCar - Murphy Automotive (2)](https://user-images.githubusercontent.com/6056563/69776467-f6e62800-1161-11ea-9d5a-4c5f82a455d7.gif)

**Comment by scaspers** [comment]
Starting to like what you had shown me before with moving the level of concern icon down in front of the "services needed".  It adds to the clarity of what we are trying to communicate.  Is this still possible?

**Comment by DanielCaspers** [comment]
Yes, done.
![image](https://user-images.githubusercontent.com/6056563/69896212-27fd5e80-1302-11ea-8440-72c831b5fac2.png)

**Comment by scaspers** [comment]
The concept of a customer marking an RS as "Service completed elsewhere" will need to be implemented later as we should have a way to notify our team members of this first.

**Comment by DanielCaspers** [comment]
Considering this issue closed for the first version of MyCar. Additional issues (#35, #36, #37) have been generated as a result of settling the V1 scope with @scaspers .
