### ISSUE TITLE
Forgot Password

### ISSUE THREAD

**Issue by DanielCaspers** [DanielCaspers/CA-Portal#26]
**Motivation**
Customers shall be able to recover their account password, should they forget it.

**Acceptance criteria**
TBD

**Comment by YoMurphy** [comment]
Approve

**Comment by DanielCaspers** [comment]
@scaspers I can't continue with estimating this task until you define it. Could you either explain the flow over a call or take your hand at editing my comment (or leaving one here for me to paste in as a req).

**Comment by scaspers** [comment]
I will be looking into adding this to the API login functionality.  Leave this and #21 out of scope for now.

**Comment by scaspers** [comment]
Method 1:
For login the user is redirected to https://d3api.murphyauto.net/api/v2/auth/login with the appkey passed (header or as URL var).  The forgot password flow is handled from there.  Once a user successfully logs in they are redirected to the mycar app (URL assoc with the appkey in the auth system) with an access_code included.  The access_code is then used in an api call to the auth/token endpoint and exchanged for am authToken for the user to use during their session.

Method 2:
Use the auth/resetpw endpoint with to provide users registered email address or phone number if successful the auth system will email the user a password reset link which will link to a page maintained by the auth system that allows the user to enter a new password.  At this point the user would need to return to the mycar login and enter credentials.

**Comment by DanielCaspers** [comment]
@scaspers, to clarify, can we do the following flow using Method 2?

1. User navigates to "My account" page.
2. Clicks on "Change Password" button, likely in a toolbar.
3. Button triggers a confirmation dialog, explaining that the next steps will be in the primary email account, and that they will be logged out. 
4. They confirm the dialog, which will send a POST auth/resetpw and also log them out.
5. They follow the email you send them with instructions.
6. They login to MyCar with updated credentials?

**Comment by scaspers** [comment]
Your suggested flow should work.

**Comment by DanielCaspers** [comment]
Closed per over-the-shoulder acceptance from Steve on 12/6/2020.  OAuth flow was used to achieve this goal.
