### ISSUE TITLE
Authentication Workflows

### ISSUE THREAD

**Issue by DanielCaspers** [DanielCaspers/CA-Portal#32]
Complete the needed workflows to have a fully functioning, secure app

- [x] Login
- [x] Logout
- [x] Refresh user's auth token on first HTTP 401
- [x] Navigate back into the app on Token Refresh success
- [x] Navigate to login page on Token Refresh Failure

**Comment by scaspers** [comment]
The JWT has been updated for MyCar.  "clientIDs" is now added and includes a list of clientID's in the form of {cono 3 digits}{clientID 6 digits} example: 004001624.
Also, the firstName & lastName have been removed and replaced with clientName as the system does not have separate fields for first & last.

**Comment by DanielCaspers** [comment]
This now functions and meets the the minimum viable product specification for the auth system.

Further improvements can be made via separate tickets as needed if something comes up on a real deployment.
