### ISSUE TITLE
Analytics - Page Tracking and Contact Info

### ISSUE THREAD

**Issue by DanielCaspers** [DanielCaspers/CA-Portal#37]
As discussed with @scaspers. we should have a means of tracking user conversion on contacting us from the vehicles list to in order to determine whether users are contacting about recommended services when they have questions.

**Requirements**
1. There should exist a click tracker on all of the contact links
2. There should exist generic page tracking within the single page app to show us where users navigate to. 
3. There should exist a click tracker on the appointment scheduling flow when the user inquires about rental cars over the phone. 

**Action Items**
1. @scaspers will provide a Google analytics project key of his choosing.

**Comment by DanielCaspers** [comment]
@scaspers I've included changes for this which I believe will work for you, though I was unable to validate them in my local environment. Please do the following.

1) Review the latest commit associated with this ticket to confirm that the tracking IDs and the click tracking I put in works as you expect.

2) Deploy the build to confirm it is sending the events appropriately to your production project. 

3) If all analytics look good, close out this ticket. Else, leave a comment here describing what needs addressing.

**Comment by scaspers** [comment]
Deployed the build to mycar2.murphyauto.net.
trackingID for mycar is UA-10667959-7

**Comment by DanielCaspers** [comment]
@scaspers it looks like it isn't tracking in production anywhere either. I have more to investigate from the app side. Not sure what is different about how I set this up from the public inspection report code wise....

**Comment by DanielCaspers** [comment]
@scaspers go ahead and take the latest build from the pipeline.
https://dev.azure.com/DanielCaspers/Murphy%20Automotive/_build/results?buildId=49&view=artifacts&type=publishedArtifacts
 I can now verify it is sending analytics from my environment. 

The one notable difference with this current setup is it means whenever I click through these features locally with tracking, it will send to your production analytics project and not to a dummy test project you've made. I'll be correcting that later on. 

For now, please verify that you find my existing event tracking sensible and that it meets your needs. If so, please close this ticket.

**Comment by scaspers** [comment]
I see the tracking activity in devtools for all pages but GA is only showing when I click the VIP page for some reason.

**Comment by scaspers** [comment]
Looks like tracking IS functioning.  The "Realtime" reporting appears to be buggy.

**Comment by DanielCaspers** [comment]
Current analytics implementation satisfies requirements. #40 has been split off from this effort and will be handled during a different milestone.
