### ISSUE TITLE
Email Us link in Sidenav

### ISSUE THREAD

**Issue by DanielCaspers** [DanielCaspers/CA-Portal#38]
We missed in our global requirements to have an email us link in the sidenav. 

In addition to allowing customers to call and text, they should also be able to email us!

This was scoped into the first mycar release per #25 in favor of more specific contact methods for the start. 

**Action Required**
1. @scaspers must provide an email address as part of the /conos endpoint for this feature to be completed.

**Comment by scaspers** [comment]
new field (emailAddress) added to conos endpoint.

**Comment by DanielCaspers** [comment]
This is now resolved and will open the user's default mailto app.
