### ISSUE TITLE
Vehicle History/Inspections/Billing - Provide Parts Description

### ISSUE THREAD

**Issue by DanielCaspers** [DanielCaspers/CA-Portal#45]
**Motivation**
Customers should be able to view a list of parts used for their vehicle for any given work order so that they can identify the relevant invoice.

**Acceptance Criteria**
1. A parts description shall be listed for each invoice
1.1 When the accordion is expanded...
1.1.1 the parts description shall be shown as a bulleted list field on the accordion panel item
1.2.1 If the viewport is desktop size...
1.2.1.1 The description shall only display 3 total items.
1.2.1.2 Items shall be displayed first from the labor description, followed by the parts description, until 3 total items have been selected to display
1.3 When an accordion is collapsed and the viewport is  desktop size...
1.3.1 Items from 1.2.1.1 and 1.2.1.2 are in effect
2. Each parts description item shall be searchable

**Comment by scaspers** [comment]
"vehiclehist" endpoint updated to include "partsDesc" for parts descriptions.
