### ISSUE TITLE
Vehicle History/Inspections/Billing - Vehicle History by Client Improvements

### ISSUE THREAD

**Issue by DanielCaspers** [DanielCaspers/CA-Portal#46]
**User Scenario**
As a user, when I have client numbers at multiple stores, I want to be able to see all historical work orders across all of my accounts.

**Background**
Current API implementation and launch scope includes an API which only supports querying by a single client ID. Combining the results from all client IDs across all companies is best handled by the API/Database side directly.   /api/v2/002/vehiclehist/client/002010015?$limit=300

**Acceptance Criteria**
1. When selecting the "All of my vehicles" dropdown filter, and on initial page load, history entries across all of my company numbers and client IDs shall be displayed.

**Comment by scaspers** [comment]
resolved with D3-API update

**Comment by scaspers** [comment]
This is now resolved with updates to the API vehiclehistory endpoint
