### ISSUE TITLE
Improve long load time for ALL vehicle history

### ISSUE THREAD

**Issue by scaspers** [DanielCaspers/CA-Portal#49]
We are thinking of limiting the number of records returned to 50 rather than 300.  The issue is that the API is taking an unacceptable amount of time creating invoice links for the history records.  If we limit the number we could add a message to the bottom of the list (if the record count=limit) letting the user know to contact us if they need older records .

Another thought is to limit the records to only those that apply to the current vehicle list. This would need to be done at the API.

**Comment by DanielCaspers** [comment]
@scaspers 
Would you rather have a "load more" button at the bottom of the list or some other pattern tried out to make the initial count hit within the correct amount of time? You can cross-reference my thinking with OData spec for some ideas.

For example, first request could be _myUrl?$top=25_. On clicking load more, second request could be _myUrl?$top=25&$skip=25_, etc.

Also, not sure if this makes sense with your implementation, but consider if it makes sense to cache the invoice URL once it is generated to avoid re-computing it again in the future. That might help especially if users often revisit this view. It would make future page navigations here cheaper.

**Comment by scaspers** [comment]
@DanielCaspers 
D3-API was updated to dramatically improve speed.  However, I believe it would be best to do the "more" function that you describe above also so that we do not limit the ability to see past n history items.
