### ISSUE TITLE
Add ability to delete a vehicle from MyVehicles

### ISSUE THREAD

**Issue by scaspers** [DanielCaspers/CA-Portal#50]
Option in the menu to delete a vehicle.  Use a confirmation before deleting.
Will need to add this ability to API before it can be implemented in UI.

**Comment by scaspers** [comment]
**API Update** 
`DELETE /vehicles/client/{clientID}/{vehicleID}

{clientID} is 9 digit client number.

{vehicleID} is the VIN of the vehicle.  If there is no VIN in the record then it cannot be deleted using the API.

204 - No Content returned on success.
`

**Comment by DanielCaspers** [comment]
Implemented in UI and was tested to be functioning. Additional back end bug fixing may be required. If additional client side bugs show up, we can re-open this or open a bug.
