### ISSUE TITLE
My Coupons: Add exclusive offers indication, improve coupon categorization

### ISSUE THREAD

**Issue by YoMurphy** [DanielCaspers/CA-Portal#56]
Just my opinion but I'd suggest changing the "General Offers" header on the My Coupons page to "Special Offers" or "Online Offers". The Term General I feel implies a lesser value or that there may be better offers elsewhere.

**Comment by DanielCaspers** [comment]
@YoMurphy how about "VIP Rewards"?

**Comment by scaspers** [comment]
or "VIP Specials"

**Comment by YoMurphy** [comment]
VIP Specials may work too, the reality is that these are the same offers on our website. I don't know if I'd consider them Exclusive, VIP or a Reward. We sometimes promote the following tag "Our best offers are found online".  It's more wordy, but it sums it up. It also doesn't need a title at all, or does it?

**Comment by DanielCaspers** [comment]
I could remove both titles, and just make sure all tire offers come last?

**Comment by YoMurphy** [comment]
The order is not important. For symmetry with our website, just label the Menu and the Page "Specials"

**Comment by DanielCaspers** [comment]
1. Added Exclusive Offer Banner if an exclusive offer exists. 
2. Improved grid handling of coupons with improved margins around coupons, and guttering for columns on larger viewports
3. Added empty state for when no coupons are available.
4. Removed separation of coupons by category
5. Removed extra headers around the coupons page.
