### ISSUE TITLE
Schedule not working on some\one

### ISSUE THREAD

**Issue by scaspers** [DanielCaspers/CA-Portal#63]
In my account the GMC truck will not POST to orders.

javascript error:
main.403c9c05a7a2918bb039.js:2 ERROR TypeError: this.issuesFormGroup.get(...).value.map is not a function
    at t.onSubmit (main.403c9c05a7a2918bb039.js:2)
    at Object.handleEvent (main.403c9c05a7a2918bb039.js:2)
    at handleEvent (main.403c9c05a7a2918bb039.js:2)
    at j_ (main.403c9c05a7a2918bb039.js:2)
    at Object.k_ [as handleEvent] (main.403c9c05a7a2918bb039.js:2)
    at $p (main.403c9c05a7a2918bb039.js:2)
    at main.403c9c05a7a2918bb039.js:2
    at e.r [as _next] (main.403c9c05a7a2918bb039.js:2)
    at e.__tryOrUnsub (main.403c9c05a7a2918bb039.js:2)
    at e.next (main.403c9c05a7a2918bb039.js:2)
bw @ main.403c9c05a7a2918bb039.js:2
t.logError @ main.403c9c05a7a2918bb039.js:2
t.handleError @ main.403c9c05a7a2918bb039.js:2
$p @ main.403c9c05a7a2918bb039.js:2
(anonymous) @ main.403c9c05a7a2918bb039.js:2
r @ main.403c9c05a7a2918bb039.js:2
e.__tryOrUnsub @ main.403c9c05a7a2918bb039.js:2
e.next @ main.403c9c05a7a2918bb039.js:2
e._next @ main.403c9c05a7a2918bb039.js:2
e.next @ main.403c9c05a7a2918bb039.js:2
e.next @ main.403c9c05a7a2918bb039.js:2
e.emit @ main.403c9c05a7a2918bb039.js:2
e.onSubmit @ main.403c9c05a7a2918bb039.js:2
(anonymous) @ main.403c9c05a7a2918bb039.js:2
handleEvent @ main.403c9c05a7a2918bb039.js:2
j_ @ main.403c9c05a7a2918bb039.js:2
k_ @ main.403c9c05a7a2918bb039.js:2
$p @ main.403c9c05a7a2918bb039.js:2
(anonymous) @ main.403c9c05a7a2918bb039.js:2
(anonymous) @ main.403c9c05a7a2918bb039.js:2
e.invokeTask @ polyfills.6896fbeba9c8312f9853.js:2
onInvokeTask @ main.403c9c05a7a2918bb039.js:2
e.invokeTask @ polyfills.6896fbeba9c8312f9853.js:2
t.runTask @ polyfills.6896fbeba9c8312f9853.js:2
t.invokeTask @ polyfills.6896fbeba9c8312f9853.js:2
p @ polyfills.6896fbeba9c8312f9853.js:2
h @ polyfills.6896fbeba9c8312f9853.js:2
main.403c9c05a7a2918bb039.js:2 ERROR CONTEXT t {view: {…}, nodeIndex: 155, nodeDef: {…}, elDef: {…}, elView: {…}}
bw @ main.403c9c05a7a2918bb039.js:2
t.logError @ main.403c9c05a7a2918bb039.js:2
t.handleError @ main.403c9c05a7a2918bb039.js:2
$p @ main.403c9c05a7a2918bb039.js:2
(anonymous) @ main.403c9c05a7a2918bb039.js:2
r @ main.403c9c05a7a2918bb039.js:2
e.__tryOrUnsub @ main.403c9c05a7a2918bb039.js:2
e.next @ main.403c9c05a7a2918bb039.js:2
e._next @ main.403c9c05a7a2918bb039.js:2
e.next @ main.403c9c05a7a2918bb039.js:2
e.next @ main.403c9c05a7a2918bb039.js:2
e.emit @ main.403c9c05a7a2918bb039.js:2
e.onSubmit @ main.403c9c05a7a2918bb039.js:2
(anonymous) @ main.403c9c05a7a2918bb039.js:2
handleEvent @ main.403c9c05a7a2918bb039.js:2
j_ @ main.403c9c05a7a2918bb039.js:2
k_ @ main.403c9c05a7a2918bb039.js:2
$p @ main.403c9c05a7a2918bb039.js:2
(anonymous) @ main.403c9c05a7a2918bb039.js:2
(anonymous) @ main.403c9c05a7a2918bb039.js:2
e.invokeTask @ polyfills.6896fbeba9c8312f9853.js:2
onInvokeTask @ main.403c9c05a7a2918bb039.js:2
e.invokeTask @ polyfills.6896fbeba9c8312f9853.js:2
t.runTask @ polyfills.6896fbeba9c8312f9853.js:2
t.invokeTask @ polyfills.6896fbeba9c8312f9853.js:2
p @ polyfills.6896fbeba9c8312f9853.js:2
h @ polyfills.6896fbeba9c8312f9853.js:2

**Comment by DanielCaspers** [comment]
Root cause was poor array handling for when no recommended services were on a vehicle to schedule with (opened from the vehicle card).
